version: "2.0"
services:
  web:
    build: .
    container_name: go-url-shortener-server
    ports: 
      - 9200:9100
    restart: always
    environment: 
      - REDIS_HOST=redis
  redis:
    image: redis:alpine
    container_name: URL_Redis
